version: '3'
services:
    sqldata:
        image: "mcr.microsoft.com/mssql/server"
        environment:
          - SA_PASSWORD=yourStrong(!)Password
          - ACCEPT_EULA=Y
        ports:
          - "1433:1433"